### ISSUE TITLE
Ruby 2.4.1 + Rails: NoMethodError (undefined method `pr_serialize'

### ISSUE THREAD

**Issue by wellington1993** [acras/prawn_reports#5]
Ola,

estou tendo o problema abaixo:
```
NoMethodError (undefined method `pr_serialize' for 
#<Coisa::ActiveRecord_Relation:0x000055bbe1e4eb78>):
```

Imagino que em (custom_report_controller.rb:34): 
` report_content = rec.pr_serialize(get_pr_serialization_params)`

o "rec" que e um ActiveRecord_Relation deveria ter ou herdar o método "pr_serialize",
no entanto nao encontrei onde a herança esta quebrada e se tem relaçao com o Ruby e o Rails usados.

Temporariamente reimplementei o método pr_serialize de "active_record_helpers.rb"
localmente em "custom_report_controller".

Se possível gostaria de um auxilio na homologaçao da gem para ruby e rails mais recentes.

Restante do Stack trace:
```
activerecord (5.0.5) lib/active_record/relation/delegation.rb:124:in `method_missing'
activerecord (5.0.5) lib/active_record/relation/delegation.rb:94:in `method_missing'
/home/wellington/.rbenv/versions/2.5.0-dev/lib/ruby/gems/2.5.0/bundler/gems/prawn_report
```

Obrigado! :+1:

**Comment by wellington1993** [comment]
Ola,

talvez tenha passado despercebido por mim em algum ponto, mas o 
erro pode estar relacionado ao fato de que tenho um Relation ou seja
mais de um registro. Talvez tenha que usar um first, de modo que buscaria o método do objeto.

No entanto não estou certo se o método não e especifico para um conjunto de registro mesmo.
Ainda estou meio confuso em relação ao modo de uso da Gem.

Se puderem me auxiliar.
Obrigado.
